### ISSUE TITLE
Complete Rebuild for using Gists

### ISSUE THREAD

**Issue by joereddington** [joereddington/Melta#4]
I've been brainstorming for an hour, and I have an idea.  All written down. 

- [ ] bug:private in public attacks blank checkboxes
- [ ] fill out rest of this list from brainstorm

**Comment by joereddington** [comment]
###### 14/02/2017-09:24:13 GMT to 14/02/2017-10:24:16 GMT:

Been brainstorming for an hour and I have a plan. 

###### 14/02/2017-10:24:41 GMT:
First thing is to change the format for the current next actions

###### 14/02/2017-10:25:33 GMT:
First error: 

highest today
 114, 2017-02-14,  1487067901, 22, 85, 57 , 38, 7, 28, 20
current
Traceback (most recent call last):
  File "/home/joereddington/Jurgen/nextActions/commands/naCalc", line 74, in <module>
    print_count_with_args()
  File "/home/joereddington/Jurgen/nextActions/commands/naCalc", line 45, in print_count_with_args
    filter_and_print_actions(args)
  File "/home/joereddington/Jurgen/nextActions/commands/naCalc", line 32, in filter_and_print_actions
    pri_items= get_action_age_info_with_priority(tasks)
  File "/home/joereddington/Jurgen/nextActions/commands/naCalc", line 58, in get_action_age_info_with_priority
    now += scorer(row)
  File "/home/joereddington/Jurgen/nextActions/commands/naCalc", line 50, in <lambda>
    def get_action_age_info_with_priority(tasklist, scorer=lambda x:7-int(x[0]), time_print=True):
ValueError: invalid literal for int() with base 10: '- [ ] 1'
joereddington@ps488197:~$ 

###### 14/02/2017-10:26:38 GMT:
Okay, early question - do we want to change the entire format while we are here? I think not, let's just get this moving. 


###### 14/02/2017-10:29:28 GMT:
Well that was easy, suspiously easy... hmm.  Okay, next one is to set up the cron. But of course, nextActions is already in a repo, so maybe this is just a seperate directory and we have to change everything? Let's do that... 

###### 14/02/2017-10:37:44 GMT:
I've pushed, and transfered accross the file, now let's see what happens when I delete the file... 

###### 14/02/2017-10:42:26 GMT:
Working thought lists (and deleting old files...) 

###### 14/02/2017-10:46:54 GMT:
There are fewer things than you would expect, mostly because everything relies on everything else. But there are things to do. 

###### 14/02/2017-10:49:37 GMT:
I appear to have changed all the relevent files. We'll have to keep an eye on some things... 

###### 14/02/2017-10:51:17 GMT:
Now I have to solve the 'push to github with cron, but with password' issue. 

###### 14/02/2017-10:52:16 GMT:
Oh, turns out I can just throw the password in there... http://askubuntu.com/questions/306176/hourly-git-push

###### 14/02/2017-11:00:15 GMT:
Bit more complex than that. 

###### 14/02/2017-11:01:47 GMT:
Okay, I've created the command, now to add it to crons. 

###### 14/02/2017-11:02:52 GMT:
It's in, will run in the next ten minutes.  

###### 14/02/2017-11:03:17 GMT:
Okay, let's take a minute and work out where we are... 

###### 14/02/2017-11:05:15 GMT:
I think that's the first milestone wrapped up.  We can now see the gist online.

**Comment by joereddington** [comment]
###### 14/02/2017-11:06:31 GMT:
So what's next? And it's the cron setup, we can change that radically, and hopefully easily... 

###### 14/02/2017-11:10:00 GMT:
Okay, I beleive I've now set things in motion so that all of the cron tasks go into waiting. Realistically I need to test that to check that they are building up there and NOT in nextactions.md.  Once we are sure, we'll start bringing them in.  

###### 14/02/2017-11:12:31 GMT:
Nothing appears to have happened with the jurgenpush command... waiting... 

###### 14/02/2017-11:12:44 GMT:
So we're now on a waiting game. Might be a good time to deal with email... 


###### 14/02/2017-11:15:00 GMT:
So I got this...

```

On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
Everything up-to-date


```

But the push doesn't appear to have happened. Let's run it locally. 

###### 14/02/2017-11:17:55 GMT:
Maybe it only works if there is something to change. Hang on 

###### 14/02/2017-11:18:45 GMT:
I'll run it again at 20 past. 

###### 14/02/2017-11:26:24 GMT:
And it worked! 

###### 14/02/2017-11:26:32 GMT:
So what's next? 

###### 14/02/2017-11:27:15 GMT:
Is it 'work on it for a while and see what happens'? Or is it, keep plugging away until something cool happens...? 

###### 14/02/2017-11:27:50 GMT:
No, I'm halfway though 
###### 14/02/2017-11:28:22 GMT:
I've just closed naUpdate down, shame, was a nice bit of code. 

###### 14/02/2017-11:28:40 GMT:
So, we're now...

###### 14/02/2017-11:32:45 GMT:
Okay yeah, (I've been writing down some streach goals...)  I think we're on 'just work on it for a while'. The obvious thing that is now harder is keeping up with Jurgen.md - that was a really useful thing, can we put that in gist comments? 

###### 14/02/2017-11:35:12 GMT:
Okay, there are gist comments, but I'm unsure if we can play them that way.  We'd need to merge things... I feel like we're better just working off a log, and then we can add things later.  We're in the habit of typing now... That works.  Let's let that ride - we can go directly to the comments section there now...

**Comment by joereddington** [comment]
###### 14/02/2017-16:12:39 GMT:
I'm back, and I'm interested in building a bit more on this. 

###### 14/02/2017-16:13:06 GMT:
The date format is massive and I'm reducing it. 

###### 14/02/2017-16:16:56 GMT:
From 
2017-02-14 (Tue)  - 16:17:00
17-02-14 16:16

which is much easier to handle. Now to see what breaks 

###### 14/02/2017-16:19:31 GMT:
Turns out the cron thing wasn't working. Let me just deal with that. 

###### 14/02/2017-16:24:20 GMT:
Was easier than expected. 

###### 14/02/2017-16:25:51 GMT:
Right, let's make it count towards a deadline NOT away from a thing. 

###### 14/02/2017-16:33:43 GMT:
There is a lot of doubled up content here.  Really needs a rewrite. 

###### 14/02/2017-16:34:44 GMT:
But I think I handled that. 

###### 14/02/2017-16:36:47 GMT:
Okay, is now the point that we start merging files?  And can we do that in an entirely new directory? 


###### 14/02/2017-16:37:19 GMT:
Yes. 

###### 14/02/2017-16:39:43 GMT:
So I've cloned the local repo, and I'm about to just switch all of the paths so that the new versions of things are triggered... 

###### 14/02/2017-16:44:39 GMT:
and the paths have now updated. So.

###### 14/02/2017-16:45:58 GMT:
I've now updated the crons. Let's find out what they do and if we need them. First up naLog

###### 14/02/2017-16:46:38 GMT:
Turns out I already deleted that. 

###### 14/02/2017-16:47:47 GMT:
trActions fails, and appears to be dealing with emails anyway. 

###### 14/02/2017-16:51:15 GMT:
Oh, trRealtimes is quite useful, keeping that. 

###### 14/02/2017-16:52:00 GMT:
I get a strong suspison that some of the files in the old jurgen haven't been committed, I should go carefully. 

###### 14/02/2017-16:53:07 GMT:
And this directory is a mess.  (The tracking one). Data and code are in the same place, commands are seperate to scripts. Poor. 

###### 14/02/2017-16:55:05 GMT:
I've put the scripts in the commands directory. Moving over to the nextactions directory. 

- [ ] still lots of data to be removed from the repo - all_added_actions is one. 

###### 14/02/2017-16:57:07 GMT:
Now, I've got a bit list of commands here, and I need to do some purging. 

###### 14/02/2017-17:00:03 GMT:
NaFuture was an interesting one. Impressed na88 still works. I'm wondering at what point I just have to pick a file and make it bigger... 

###### 14/02/2017-17:00:59 GMT:
Unhelpfully, some of these are python and some are scripts. 

###### 14/02/2017-17:02:26 GMT:
naCalc is, oddly, the largest script. Maybe I should be bringing these down.. No, let's leave them where they are... 

###### 14/02/2017-17:04:00 GMT:
Interesting, so naCalc already has a set of arguments and stuff in it. I think this might be the starting point, but let's check 

###### 14/02/2017-17:05:08 GMT:
Worth asking now, what do we want a 'jurgen' comand to do.  

- [x] Print sorted tasks
- [x] Print priority ages 
- [ ] Give the 'next' task. 
- [ ] print the total times 
- [ ] split all of these by age band or context. 
- [ ] add a task. 
- [ ] tell us how much time we have spent working on this today 

- [ ] the below have been removed, but them back

``
   parser.add_argument( '-a', action='store_true', help="Gives all numbers")
  1     parser.add_argument( '-m', action='store_true', help="Gives the average as well")
``

###### 14/02/2017-17:15:08 GMT:
Still going... 
###### 14/02/2017-17:22:22 GMT:
So naCalc is taken care of, as is naSort (for now) what else do we have? 

###### 14/02/2017-17:29:33 GMT:
###### 14/02/2017-17:39:33 GMT:
na is the interesting one. or rather it's now naWaiting that is the issue  

###### 14/02/2017-17:43:58 GMT:
No idea if the cron is going to work out, but it's in now... :) 

###### 14/02/2017-17:49:34 GMT:
Doing some refactoring as we go. 

###### 14/02/2017-17:51:53 GMT:
sort is now filtering by context, but NOT by age. Let's sort that out. 


###### 14/02/2017-17:54:46 GMT:
###### 14/02/2017-18:04:46 GMT:
Some good refactoring just happened there, much easier to understand now. 

###### 14/02/2017-18:14:25 GMT:

###### 14/02/2017-18:16:25 GMT:
But having problems making it work!

###### 14/02/2017-18:23:34 GMT:
Solved. Commiting. 
###### 14/02/2017-18:30:07 GMT:
Melta now deals with random selection, including with any criteria. 


###### 14/02/2017-18:30:48 GMT:
Next is naNext,  orginally naNext just gave the highest priority purple, but I can use the filtering to be more specific so 

     melta -d 3 next 

will give the highest priority purple and  
     melta -d 7 next 

will give the highest priority red. 

(now I'm thinking all this could be javascript, but we'll get on to that) 

###### 14/02/2017-18:35:50 GMT:
naNext is now in as well.  

###### 14/02/2017-18:36:41 GMT:
I'm looking at naCount, and I feel like we N'T use it anywhere.. getting rid. 

###### 14/02/2017-18:37:05 GMT:
Relatively sure that we N'T need na88 because it turns out that's only a 60 second vim trick.  Should have realised that at the time. 

###### 14/02/2017-18:37:52 GMT:
Jurgen_sessions is big and in the way, but it's also going to be folded into the Vision project fairly soon, so I can ignore it for now.  I might let it keep going... 

###### 14/02/2017-18:43:09 GMT:
naTime is interesting. It's awkward and currently doesn't work. Maybe I just reduce down. 

###### 14/02/2017-18:48:17 GMT:
Turns out it was easy if we dropped some of the printing and we relied on the user.  Removing (did use some hours and minutes code. 

###### 14/02/2017-18:55:28 GMT:
Okay, that's the last one gone.  All of the libraries as well. At some point I need to put it though a proper code beutifier (and tester) to see what we have.  It's also 160 lines long 

###### 14/02/2017-18:56:22 GMT:
Question is at this point, do I need a commands directory? I think I don't. 

###### 14/02/2017-18:57:43 GMT:
Interesting. I do think all_added_actions is a reasonable thing to have, but it might be a gist in it's own right (logically so, everything that has been public once) so it shoudl be the case that 

- [ ] all_added_actions in it's own gist.  

###### 14/02/2017-18:59:56 GMT:
Unsure what to do with cron triggered scripts. Actually I've decided. Both the examples I have are ones designed to make me sound smarter. I'll drop them. 

###### 14/02/2017-19:01:01 GMT:
Waiting_actions.csv has started to work. Although it's in the wrong directory and, and has the wrong extension. 

###### 14/02/2017-19:03:51 GMT:
Oh hey, I had a readme. It was a bit more. Will need a new one later. 

###### 14/02/2017-19:07:27 GMT:
Back looking at the tracking directory. 

###### 14/02/2017-19:08:48 GMT:
Hmm. so we are kind of left with just the files for creating the graphiscs  (which might have stopped working...) which are kind of in the way and kind of... seperate mentally. There was always a reason why they where in another directory. 
###### 14/02/2017-19:11:28 GMT:
There's lots I fail to understand about that whole bit.  Think that I should leave it until we do the full switch over to javascript.  Which I could totally do now if anyone was asking... Maybe another day. 

###### 14/02/2017-19:13:09 GMT:
Hmmm. Data should be in one place, source another, that's simple. Let's do that. 

###### 14/02/2017-19:15:04 GMT:
Yes, I now have a data directory (which in all cases, could be gists, certainly the priority part is, and if nextactions can be public then so can all_added_actions) 

###### 14/02/2017-19:19:32 GMT:
Has all_added_actions NOT been updated since may...

###### 14/02/2017-19:25:44 GMT:
More moving things around... 

###### 14/02/2017-19:27:29 GMT:
Hmmm. I do really want to put the data in it's own repo. but it seems odd somehow. 

###### 14/02/2017-19:29:57 GMT:
I could just go the whole way and do the charting now? 

###### 14/02/2017-19:30:20 GMT:
I should also tidy up the directory for joereddington.com 

###### 14/02/2017-19:33:15 GMT:
Found a place for the data. 

###### 14/02/2017-19:35:57 GMT:
Going to push the code shortly. 
###### 14/02/2017-19:41:36 GMT:
Crap! 
###### 14/02/2017-19:44:29 GMT:
Left my password in briefly, but that did teach me to use filter-branch, which was fun. 

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch jurgenpush' --prune-empty --
tag-name-filter cat -- --all

git push origin --force --all

###### 14/02/2017-19:45:01 GMT:
Anyway. I should update that, and I'll add a task now. 

###### 14/02/2017-19:48:27 GMT:
So what now? is it to completely redo the charts or is there something else? (We should also check the damn thing is working after we moved everything...) 

###### 14/02/2017-19:49:54 GMT:
Let's at least have a look at the charts. 

###### 14/02/2017-19:51:46 GMT:
There's a thing, javascript isn't going to read this file unless it's already in javascript. We'll have to deal with that. 

###### 14/02/2017-20:00:22 GMT:
Oh wait, obviously it can, hang on. 

###### 14/02/2017-20:02:35 GMT:
(upvoted this: http://stackoverflow.com/a/35382510/170243) 


###### 14/02/2017-20:06:50 GMT:
###### 14/02/2017-20:16:50 GMT:
I am completely making this up as I go along... 

###### 14/02/2017-20:30:57 GMT:
Still going

###### 14/02/2017-20:34:28 GMT:
Okay, I have a very busy graph

###### 14/02/2017-20:36:54 GMT:
And indeed. It's looking like there might just be too much data for the chart.js approach to cope with... 


###### 14/02/2017-20:42:00 GMT:
Yeah, this is hidiously slow, evern for a week's set of readings. it's still animating. 


###### 14/02/2017-20:46:05 GMT:
So I deleted a lot of points to see when it would start working better, but it looks like the same number of points...

###### 14/02/2017-20:48:01 GMT:
Okay, there was some cactching going on.  Now, with 180 points, it kind of works... but 180 points is only 26ish a day, that's NOT very clear, and we want five graphs... 

###### 14/02/2017-20:54:56 GMT:
Yeah - this is too slow and too ugly and I remain unimpressed.  Real shame actually, could have been beutiful.  

###### 14/02/2017-20:55:55 GMT:
Anyway. Signing off for the day.
